[tool.isort]
profile = "black"
known_first_party = ["wordmaze"]
multi_line_output = 3
line_length = 79
float_to_top = true
remove_redundant_aliases = true

[tool.black]
include = '\.pyi?$'
line-length = 79
skip-string-normalization = true

[tool.unimport]
gitignore = true
ignore_init = true
include_star_import = true
remove = true
requirements = true

[tool.mypy]
ignore_missing_imports = true
plugins = ["dataclassy.mypy"]

[tool.coverage.report]
exclude_lines = [
	"@overload"
]

[tool.commitizen]
tag_format = "v$major.$minor.$patch$prerelease"
update_changelog_on_bump = true
version = "0.3.6"
version_files = ["VERSION"]
